name: Build WhatsApp Binary with GLIBC 2.31

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye  # GLIBC 2.31
    steps:
      - name: Install dependencies
        run: |
          apt update
          apt install -y curl git gcc make wget unzip
          curl -OL https://go.dev/dl/go1.22.3.linux-amd64.tar.gz
          tar -C /usr/local -xzf go1.22.3.linux-amd64.tar.gz
          echo "export PATH=$PATH:/usr/local/go/bin" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build binary
        run: |
          export PATH=$PATH:/usr/local/go/bin
          go build -buildvcs=false -o whatsapp ./src

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: whatsapp-binary
          path: whatsapp
