name: Build go-whatsapp-web-multidevice (Static Binary)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # tidak perlu ubuntu-20.04 karena tidak pakai GLIBC
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Build static binary
        run: |
          cd src
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -buildvcs=false -o whatsapp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: whatsapp-binary
          path: src/whatsapp
